sudo: true
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
    allow_failures:
        - php: hhvm
    fast_finish: true

branches:
  only:
    - /^8.x/


before_install:
  - export ISLANDORA_DIR=$TRAVIS_BUILD_DIR
  - echo 'always_populate_raw_post_data = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
#  - $TRAVIS_BUILD_DIR/tests/scripts/travis_setup.sh
  - composer install
  - php vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer


script:
  - $ISLANDORA_DIR/tests/scripts/line_endings.sh .
  - php vendor/bin/phpcs --standard=Drupal *.module src
  - php vendor/bin/phpcpd --names *.module,*.inc,*.test,*.php --exclude=vendor .

notifications:
  irc:
    channels:
      - "irc.freenode.org#islandora"
    on_success: change
    on_failure: always
    skip_join: true
